# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Thu Sep  4 10:42:10 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

#from PySide import QtCore, QtGui
from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(342, 323)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(342, 323))
        MainWindow.setMaximumSize(QtCore.QSize(342, 323))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/wow_rogue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hostsChangeButton = QtGui.QPushButton(self.centralwidget)
        self.hostsChangeButton.setEnabled(True)
        self.hostsChangeButton.setGeometry(QtCore.QRect(230, 270, 99, 23))
        self.hostsChangeButton.setObjectName("hostsChangeButton")
        self.hostsList = QtGui.QListView(self.centralwidget)
        self.hostsList.setGeometry(QtCore.QRect(10, 50, 321, 211))
        self.hostsList.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.hostsList.setObjectName("hostsList")
        self.hostsPathLabel = QtGui.QLabel(self.centralwidget)
        self.hostsPathLabel.setGeometry(QtCore.QRect(10, 30, 321, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.hostsPathLabel.setFont(font)
        self.hostsPathLabel.setCursor(QtCore.Qt.IBeamCursor)
        self.hostsPathLabel.setText("")
        self.hostsPathLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.hostsPathLabel.setObjectName("hostsPathLabel")
        self.hostsLine = QtGui.QLineEdit(self.centralwidget)
        self.hostsLine.setGeometry(QtCore.QRect(10, 10, 321, 22))
        self.hostsLine.setReadOnly(True)
        self.hostsLine.setObjectName("hostsLine")
        self.refreshListButton = QtGui.QPushButton(self.centralwidget)
        self.refreshListButton.setGeometry(QtCore.QRect(10, 260, 31, 31))
        self.refreshListButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshListButton.setIcon(icon1)
        self.refreshListButton.setIconSize(QtCore.QSize(36, 36))
        self.refreshListButton.setObjectName("refreshListButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 342, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionQuit = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon2)
        self.actionQuit.setIconVisibleInMenu(True)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPath = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/configure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPath.setIcon(icon3)
        self.actionPath.setObjectName("actionPath")
        self.actionAbout_Hosts_Changer = QtGui.QAction(MainWindow)
        self.actionAbout_Hosts_Changer.setIcon(icon)
        self.actionAbout_Hosts_Changer.setObjectName("actionAbout_Hosts_Changer")
        self.menuFile.addAction(self.actionQuit)
        self.menuSettings.addAction(self.actionPath)
        self.menuHelp.addAction(self.actionAbout_Hosts_Changer)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Hosts Changer", None, QtGui.QApplication.UnicodeUTF8))
        self.hostsChangeButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Change hosts to selected file", None, QtGui.QApplication.UnicodeUTF8))
        self.hostsChangeButton.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.hostsPathLabel.setToolTip(QtGui.QApplication.translate("MainWindow", "Hosts list directory", None, QtGui.QApplication.UnicodeUTF8))
        self.hostsLine.setToolTip(QtGui.QApplication.translate("MainWindow", "Hosts file", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshListButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Refresh file list", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPath.setText(QtGui.QApplication.translate("MainWindow", "&Path", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPath.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Hosts_Changer.setText(QtGui.QApplication.translate("MainWindow", "About Hosts Changer", None, QtGui.QApplication.UnicodeUTF8))

